#!/bin/bash

###########################################################
# This script prints a one-time snapshot of swap usage
# by processes.
###########################################################

if [ "$EUID" -ne "0" ]; then
	echo "I was called by UID $EUID but I *must* be run by root. Calling sudo right now"
	echo "If sudo fails with 'command not found', please give it the full path instead"
	echo sudo $0
	sudo $0
	exit 0
fi

( ps -eo pid= |\
xargs -n1 -P0 -i awk -v myPID={} '
	BEGIN { progpid=myPID; c="ps -o cmd= -p " myPID; c|getline progfull; close(c); split(progfull, progname, " "); }
	/^Swap:/ { total+=$2; }
	END { KBswap=total; MBswap=rshift(total,10);
		if(MBswap != 0) {
			printf "%dM swap used by PID %d (%s)\n", MBswap, progpid, progname[1]
		}
		else if(KBswap != 0) {
			printf "%dK swap used by PID %d (%s)\n", KBswap, progpid, progname[1]
		}
	}
' /proc/{}/smaps
) 2>/dev/null | sort -h | nl
echo "== System-wide swap report =="
grep '^Swap' /proc/meminfo

exit 0
